[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#00ff00"

# Background color for the main content area.
backgroundColor = "#010802"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#2c342d"

# Color used for almost all text.
textColor = "#ffffff"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "monospace"